// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("DeviceInfo")]
    public partial class DeviceInfo : RecordBase<DeviceInfo, int>
    {
        [Key]
        public int Id { get; set; }
        public string DeviceNo { get; set; }
        public string DriverName { get; set; }
        public string WorkingHours { get; set; }
        public string Phone { get; set; }
        public string Area { get; set; }
        public string Remark { get; set; }
        public float Load { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public bool IsValid { get; set; }
        public bool IsDelete { get; set; }
        public double InitialLatitude { get; set; }
        public double InitialLongitude { get; set; }

		static DeviceInfo ()
		{
			TableName = "DeviceInfo";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(DeviceInfo));
		}
    }
}
