// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("DriverZip")]
    public partial class DriverZip : RecordBase<DriverZip, int>
    {
        [Key]
        public int Id { get; set; }
        public int? Device_Id { get; set; }
        public int? ZipGroup_Id { get; set; }

		static DriverZip ()
		{
			TableName = "DriverZip";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(DriverZip));
		}
    }
}
