// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("DriverSalaryFulltime")]
    public partial class DriverSalaryFulltime : RecordBase<DriverSalaryFulltime, int>
    {
        [Key]
        public int Id { get; set; }
        public int DeviceID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyRegNo { get; set; }
        public string DriverName { get; set; }
        public string DriverIC { get; set; }
        public string DriverEmployeeID { get; set; }
        public string FileRefNo { get; set; }
        public string IssueDate { get; set; }
        public string PayFor { get; set; }
        public decimal EarningBasicWage { get; set; }
        public decimal EarningBonus { get; set; }
        public decimal EarningSubsidy { get; set; }
        public decimal EarningOthers { get; set; }
        public decimal? ForeignWorkerLevy { get; set; }
        public decimal DeductionRepair { get; set; }
        public decimal DeductionFine { get; set; }
        public decimal DeductionLeaveDeduction { get; set; }
        public decimal DeductionTax { get; set; }
        public decimal DeductionCPF { get; set; }
        public decimal DeductionOther { get; set; }
        public decimal ClaimPetrol { get; set; }
        public decimal ClaimParking { get; set; }
        public decimal ClaimTopup { get; set; }
        public decimal ClaimServices { get; set; }
        public decimal? ClaimClaim { get; set; }
        public decimal ClaimOther { get; set; }
        public decimal? CPFEmployee { get; set; }
        public decimal? CPFEmployer { get; set; }
        public decimal? CPFOther { get; set; }
        public string CPFNumber { get; set; }
        public double? ALEntitlement { get; set; }
        public double? ALBonus { get; set; }
        public double? ALTaken { get; set; }
        public double? SLEntitlement { get; set; }
        public double? SLBonus { get; set; }
        public double? SLTaken { get; set; }
        public string Bank { get; set; }
        public string BankBranch { get; set; }
        public string BankAccount { get; set; }
        public string Terms { get; set; }
        public string CheckNo { get; set; }
        public double? Cash { get; set; }

		static DriverSalaryFulltime ()
		{
			TableName = "DriverSalaryFulltime";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(DriverSalaryFulltime));
		}
    }
}
