// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("History")]
    public partial class History : RecordBase<History, int>
    {
        [Key]
        public int Id { get; set; }
        public string DriverName { get; set; }
        public int? TaskInfo_Id { get; set; }

		static History ()
		{
			TableName = "History";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(History));
		}
    }
}
