// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("Images")]
    public partial class Images : RecordBase<Images, int>
    {
        [Key]
        public int ID { get; set; }
        public string ImagePath { get; set; }

		static Images ()
		{
			TableName = "Images";
			PrimaryKey = "ID";
			TableMappingInfo.Create(typeof(Images));
		}
    }
}
