// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("JobInfo")]
    public partial class JobInfo : RecordBase<JobInfo, int>
    {
        [Key]
        public int Id { get; set; }
        public string NickName { get; set; }
        public string DeliveryToName { get; set; }
        public string Address { get; set; }
        public bool isLocked { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public DateTime PayDate { get; set; }
        public double Weight { get; set; }
        public decimal PayTotal { get; set; }
        public string Memo { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string ShipmentId { get; set; }
        public string CustomerId { get; set; }
        public bool IsConfirmed { get; set; }
        public int ScheduleType { get; set; }
        public DateTime DueDate { get; set; }
        public string Source { get; set; }
        public int? UserId { get; set; }

		static JobInfo ()
		{
			TableName = "JobInfo";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(JobInfo));
		}
    }
}
