// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("MailStatus")]
    public partial class MailStatusTable : RecordBase<MailStatusTable, int>
    {
        [Key]
        public int Id { get; set; }
        public int TaskId { get; set; }
        public string EmailAddress { get; set; }
        public string MailStatus { get; set; }

		static MailStatusTable ()
		{
			TableName = "MailStatus";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(MailStatusTable));
		}
    }
}
