// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("SalaryPlan2")]
    public partial class SalaryPlan2 : RecordBase<SalaryPlan2, int>
    {
        [Key]
        public int Id { get; set; }
        public double FirstThresholdWeight { get; set; }
        public double FirstThresholdRate { get; set; }
        public double SecondWeightBlock { get; set; }
        public double SecondWeightRate { get; set; }

		static SalaryPlan2 ()
		{
			TableName = "SalaryPlan2";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(SalaryPlan2));
		}
    }
}
