// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("SystemParameter")]
    public partial class SystemParameter : RecordBase<SystemParameter, int>
    {
        [Key]
        public int Id { get; set; }
        public string ParameterKey { get; set; }
        public string ParameterDesc { get; set; }
        public string ParameterValue { get; set; }
        public int? DeviceId { get; set; }
        public int UserId { get; set; }
        public bool IsHtmlValue { get; set; }

		static SystemParameter ()
		{
			TableName = "SystemParameter";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(SystemParameter));
		}
    }
}
