// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("UsageSummary")]
    public partial class UsageSummary : RecordBase<UsageSummary, int>
    {
        [Key]
        public int Id { get; set; }
        public int EmailCount { get; set; }
        public int SmsCount { get; set; }
        public decimal EmailUnitPrice { get; set; }
        public decimal SmsUnitPrice { get; set; }

		static UsageSummary ()
		{
			TableName = "UsageSummary";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(UsageSummary));
		}
    }
}
