// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("UsageDetail")]
    public partial class UsageDetail : RecordBase<UsageDetail, int>
    {
        [Key]
        public int Id { get; set; }
        public int UsageSummaryId { get; set; }
        public int UsageType { get; set; }
        public DateTime UsedOn { get; set; }

		static UsageDetail ()
		{
			TableName = "UsageDetail";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(UsageDetail));
		}
    }
}
