// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("UserProfile")]
    public partial class UserProfile : RecordBase<UserProfile, int>
    {
        [Key]
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string ShipmentIdPrefix { get; set; }
        public string ShipperInfo { get; set; }
        public bool IsActive { get; set; }

		static UserProfile ()
		{
			TableName = "UserProfile";
			PrimaryKey = "UserId";
			TableMappingInfo.Create(typeof(UserProfile));
		}
    }
}
