// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("Waybill")]
    public partial class Waybill : RecordBase<Waybill, int>
    {
        [Key]
        public int Id { get; set; }
        public string ShiperCompanyName { get; set; }
        public string ShiperContactName { get; set; }
        public string ShiperHP { get; set; }
        public string ShiperAddress { get; set; }
        public string ShiperZipCode { get; set; }
        public string Description { get; set; }
        public string ReceiverCompanyName { get; set; }
        public string Quantity { get; set; }
        public string RefNo { get; set; }
        public int? Piece1 { get; set; }
        public double? Length1 { get; set; }
        public double? Width1 { get; set; }
        public double? Height1 { get; set; }
        public int? Piece2 { get; set; }
        public double? Length2 { get; set; }
        public double? Width2 { get; set; }
        public double? Height2 { get; set; }
        public int? Piece3 { get; set; }
        public double? Length3 { get; set; }
        public double? Width3 { get; set; }
        public double? Height3 { get; set; }
        public int? ShipmentType { get; set; }
        public string AdditionalSvc1 { get; set; }
        public string AdditionalSvc2 { get; set; }
        public double? SvcCharge1 { get; set; }
        public double? SvcCharge2 { get; set; }
        public int TotalPackage { get; set; }
        public double ChargableWeight { get; set; }
        public int Currency { get; set; }
        public double ActualWeight { get; set; }
        public double TotalCharge { get; set; }
        public int PaymentType { get; set; }
        public string AccountNo { get; set; }
        public string ThirdPartyCode { get; set; }
        public string PickedBy { get; set; }
        public string DeliveredBy { get; set; }
        public int? ShiperSignatureImgID { get; set; }
        public int? RecSignatureImgID { get; set; }
        public string Remark { get; set; }
        public DateTime CreatedOn { get; set; }

		static Waybill ()
		{
			TableName = "Waybill";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(Waybill));
		}
    }
}
