// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("webpages_Roles")]
    public partial class webpages_Roles : RecordBase<webpages_Roles, int>
    {
        [Key]
        public int RoleId { get; set; }
        public string RoleName { get; set; }

		static webpages_Roles ()
		{
			TableName = "webpages_Roles";
			PrimaryKey = "RoleId";
			TableMappingInfo.Create(typeof(webpages_Roles));
		}
    }
}
