// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("webpages_OAuthMembership")]
    public partial class webpages_OAuthMembership : RecordBase<webpages_OAuthMembership, string>
    {
        [Key]
        public string Provider { get; set; }
        public string ProviderUserId { get; set; }
        public int UserId { get; set; }

		static webpages_OAuthMembership ()
		{
			TableName = "webpages_OAuthMembership";
			PrimaryKey = "Provider";
			TableMappingInfo.Create(typeof(webpages_OAuthMembership));
		}
    }
}
