// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("ZipGroup")]
    public partial class ZipGroup : RecordBase<ZipGroup, int>
    {
        [Key]
        public int Id { get; set; }
        public string code { get; set; }
        public string area { get; set; }
        public string ShouldInclude { get; set; }
        public string ShouldExclude { get; set; }

		static ZipGroup ()
		{
			TableName = "ZipGroup";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(ZipGroup));
		}
    }
}
