// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Coat.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using Coat.Base;
using Coat.Base.SqlMapping;
using Dapper;
using Dapper.Contrib.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace d2d
{
    [Table("ZipLocation")]
    public partial class ZipLocation : RecordBase<ZipLocation, int>
    {
        [Key]
        public int Id { get; set; }
        public string ZipCode { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }

		static ZipLocation ()
		{
			TableName = "ZipLocation";
			PrimaryKey = "Id";
			TableMappingInfo.Create(typeof(ZipLocation));
		}
    }
}
